# Generated by Django 3.0.6 on 2020-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kavithai',
            name='image',
            field=models.ImageField(upload_to='Post/static/Post/images/kavidhai'),
        ),
    ]
