# Generated by Django 3.0.6 on 2020-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200515_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='pictures/gallery'),
        ),
        migrations.AlterField(
            model_name='kadhai',
            name='image',
            field=models.ImageField(upload_to='Pictures/kadhai'),
        ),
        migrations.AlterField(
            model_name='katturai',
            name='image',
            field=models.ImageField(upload_to='pictures/katturai'),
        ),
        migrations.AlterField(
            model_name='kavithai',
            name='image',
            field=models.ImageField(upload_to='Pictures/kavidhai'),
        ),
    ]
