# Generated by Django 3.0.6 on 2020-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200515_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadhai',
            name='kadhai_description',
            field=models.CharField(default='No description available', max_length=300),
        ),
    ]
