# Generated by Django 3.0.6 on 2020-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_kadhai_kadhai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_alt_text',
            field=models.CharField(default='alternate text', max_length=100),
        ),
        migrations.AddField(
            model_name='kadhai',
            name='image_alt_text',
            field=models.CharField(default='alternate text', max_length=100),
        ),
        migrations.AddField(
            model_name='katturai',
            name='image_alt_text',
            field=models.CharField(default='alternate text', max_length=100),
        ),
        migrations.AddField(
            model_name='kavithai',
            name='image_alt_text',
            field=models.CharField(default='alternate text', max_length=100),
        ),
        migrations.AlterField(
            model_name='kadhai',
            name='kadhai_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='katturai',
            name='katturai_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kavithai',
            name='kavithai_content',
            field=models.TextField(),
        ),
    ]
