# Generated by Django 3.0.6 on 2020-08-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200531_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
