# Generated by Django 3.0.6 on 2020-08-09 12:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katturai',
            name='katturai_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
