# Generated by Django 3.0.6 on 2020-05-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilePic',
        ),
    ]
